steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_POSTHOG_KEY=${_NEXT_PUBLIC_POSTHOG_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_POSTHOG_HOST=${_NEXT_PUBLIC_POSTHOG_HOST}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/infoverse/infoverse-frontend:$COMMIT_SHA'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/infoverse/infoverse-frontend:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'infoverse-frontend'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/infoverse/infoverse-frontend:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'

substitutions:
  _NEXT_PUBLIC_API_URL: 'http://localhost:5001/api/v1'
  _NEXT_PUBLIC_POSTHOG_KEY: ''
  _NEXT_PUBLIC_POSTHOG_HOST: 'https://us.i.posthog.com'
  _NEXT_PUBLIC_GOOGLE_CLIENT_ID: ''
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/infoverse/infoverse-frontend:$COMMIT_SHA'
