steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/infoverse-frontend:$COMMIT_SHA'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/infoverse-frontend:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'infoverse-frontend'
      - '--image=gcr.io/$PROJECT_ID/infoverse-frontend:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'

substitutions:
  _NEXT_PUBLIC_API_URL: 'http://localhost:5001/api/v1' # override this in your trigger

images:
  - 'gcr.io/$PROJECT_ID/infoverse-frontend:$COMMIT_SHA'
