[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_PUBLIC_API_URL = "https://infoverse-backend-84498540486.europe-west1.run.app/api/v1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

# Allow RSC prefetching
[[headers]]
  for = "/*.rsc"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"
